# This is not production worthy configuration!
# See https://grafana.com/docs/grafana/latest/datasources/postgres/

apiVersion: 1
datasources:
  - name: service-catalogue
    type: postgres
    url: postgres:5432
    user: postgres
    secureJsonData:
      password: 'not_at_all_secret'
    jsonData:
      database: postgres
      sslmode: 'disable'
      maxOpenConns: 0
      maxIdleConns: 2
      connMaxLifetime: 14400
      postgresVersion: 1000
      timescaledb: false
  - name: gdev-testdata
    isDefault: false
    type: testdata
