version: '3.9'
services:
  postgres:
    image: postgres:14.6
    ports:
      - '${DATABASE_PORT}:${DATABASE_PORT}'
    environment:
      POSTGRES_DB: ${DATABASE_HOSTNAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
  cloudquery:
    image: ghcr.io/cloudquery/cloudquery:${CQ_CLI}
    platform: linux/amd64
    depends_on:
      - postgres
    volumes:
      - ~/.aws/credentials:/.aws/credentials
      - ./dev-config/cloudquery.yaml:/dev-config.yaml
      - ~/.gu/service_catalogue/app-id:/app-id
      - ~/.gu/service_catalogue/installation-id:/installation-id
      - ~/.gu/service_catalogue/private-key.pem:/private-key.pem
    environment:
      AWS_SHARED_CREDENTIALS_FILE: '/.aws/credentials'
      CQ_POSTGRES_DESTINATION: ${CQ_POSTGRES_DESTINATION}
      CQ_AWS: ${CQ_AWS}
      CQ_GITHUB: ${CQ_GITHUB}
      CQ_SNYK: ${CQ_SNYK}
      SNYK_TOKEN: ${SNYK_TOKEN}
      GALAXIES_BUCKET: ${GALAXIES_BUCKET}
    command: sync /dev-config.yaml --log-console --log-level info
  grafana:
    image: grafana/grafana-oss:9.4.7
    depends_on:
      - postgres
    ports:
      - '3000:3000'
    volumes:
      - ./dev-config/grafana.ini:/etc/grafana/grafana.ini
      - ./dev-config/grafana-datasource.yaml:/etc/grafana/provisioning/datasources/cloudquery.yaml
