version: '3.9'
services:
  postgres:
    image: postgres:14.6
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: not_at_all_secret
  cloudquery:
    image: ghcr.io/cloudquery/cloudquery:2.5.3
    platform: linux/amd64
    depends_on:
      - postgres
    volumes:
      - ~/.aws/credentials:/.aws/credentials
      - ./dev-config/cloudquery.yaml:/dev-config.yaml
    environment:
      AWS_SHARED_CREDENTIALS_FILE: "/.aws/credentials"
    command: sync /dev-config.yaml --log-console --log-level warn
  grafana:
    image: grafana/grafana-oss:9.4.7
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    volumes:
      - ./dev-config/grafana.ini:/etc/grafana/grafana.ini
      - ./dev-config/grafana-datasource.yaml:/etc/grafana/provisioning/datasources/cloudquery.yaml
