name: Run an npm script
description: 'Run an npm script'
inputs:
  script:
    description: 'The npm script to run'
    required: true
  deployment_key:
    description: 'The private key to use for deployment'
    required: true


runs:
  using: 'composite'
  steps:

    - name: Setup Node
      uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
      with:
        node-version-file: '.nvmrc'
        cache: 'npm'
        cache-dependency-path: 'package-lock.json'

    - uses: guardian/actions-read-private-repos@8792b5279dc2e6dfb6b9aa6ba2f26b6226be444c # v0.1.1
      with:
        private-ssh-keys: ${{ inputs.deployment_key }}

    # - name: Restore cache
    #   id: cache-npm
    #   uses: actions/cache@v3
    #   env:
    #     cache-name: cache-node-modules
    #   with:
    #     # npm cache files are stored in `~/.npm` on Linux/macOS
    #     path: ~/.npm
    #     key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}

    # - if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
    - name: install remaining dependencies
      shell: bash
      run: npm i

    - name: Run script
      shell: bash
      run: npm run ${{ inputs.script }}
