openapi: 3.0.0
info:
 title: GitHub Metadata API
 description: Returns= information about The Guardian's various GitHub projects.
 version: 0.0.1
servers:
 - url: http://repos.gutools.co.uk/v1
   description: Optional server description, e.g. Main (production) server
 - url: http://repos.test.gutools.co.uk/v1
   description: Optional server description, e.g. Internal staging server for testing
paths:
 /repos:
   get:
     summary: Returns a list of repo objects, representing un-archived repositories in the guardian organisation.
     description: Optional extended description in CommonMark or HTML.
     parameters:
       - name: limit
         in: path
         description: Maximum number of entries to return
         schema:
           type : integer
           format: int64
           default: 100
           minimum: 1
           maximum: 100
       - name: offset
         in: path
         description: Pagination mechanism.
         schema:
           type : integer
           format: int64
           default: 0
           minimum: 0
     x-amazon-apigateway-integration:
       '$ref': '#/components/x-amazon-apigateway-integrations/mocked'
     responses:
       '200':
         description: A JSON array of user names
         content:
           application/json:
             schema:
               type: array
               items:
                 type: object
                 properties:
                   name:
                     type: string
                     description: Short name of the repo
                   default_branch:
                     type: string
                     description: Typically master or main.
                   topics:
                     type: array
                     items:
                       type: string
                     description: How has the repository been tagged? Used to determine production status.
                   owners:
                     type: array
                     items:
                       type: string
                     description: Which GitHub teams are designated as repository 'Owners'
       '404':
         description: An error message, if the user requests data that doesn't exist (ie the offset is too large)
         content:
           application/json:
             schema:
               type: string
       '500':
         description: Internal server error
         content:
           application/json:
             schema:
               type: string
components:
  x-amazon-apigateway-integrations:
    mocked:
      type: mock

