version: '3.9'
services:
  # This service will copy data from the CODE database, writing .sql files to the sql directory.
  # The files will then be loaded into the postgres service on launch.
  db-copy:
    build:
      context: ../../containers/db-copy
      args:
        alpine_version: 3.19.1
    volumes:
      - ~/.aws/credentials:/.aws/credentials
      - ./sql:/sql
    environment:
      AWS_CONFIG_FILE: /.aws/config
      AWS_SHARED_CREDENTIALS_FILE: /.aws/credentials
      AWS_DEFAULT_PROFILE: deployTools
      AWS_REGION: eu-west-1

      # These tables will be copied from the CODE database, and loaded into the DEV database.
      TABLES: |
        - snyk_issues
        - snyk_projects
        - galaxies_teams_table
        - github_team_repositories
        - github_teams
        - github_repositories
        - github_repository_branches
        - github_workflows
        - github_languages
        - aws_organizations_account_parents
        - aws_organizations_organizational_units
        - aws_ec2_instances
        - aws_cloudformation_stacks
  postgres:
    image: postgres:14.6
    ports:
      - '${DATABASE_PORT}:${DATABASE_PORT}'
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      # Runs the .sql files from the db-copy service on launch.
      # See https://hub.docker.com/_/postgres#:~:text=Initialization%20scripts.
      - ./sql:/docker-entrypoint-initdb.d/
    depends_on:
      db-copy:
        condition: service_completed_successfully
  cloudquery:
    build:
      context: ../../containers/cloudquery
      args:
        CQ_CLI: ${CQ_CLI}
    platform: linux/amd64
    depends_on:
      - postgres
    volumes:
      - ~/.aws/credentials:/.aws/credentials
      - ./config/cloudquery.yaml:/cloudquery.yaml
      - ~/.gu/service_catalogue/app-id:/app-id
      - ~/.gu/service_catalogue/installation-id:/installation-id
      - ~/.gu/service_catalogue/private-key.pem:/private-key.pem
    environment:
      AWS_SHARED_CREDENTIALS_FILE: '/.aws/credentials'
      CQ_POSTGRES_DESTINATION: ${CQ_POSTGRES_DESTINATION}
      CQ_AWS: ${CQ_AWS}
      CQ_GITHUB: ${CQ_GITHUB}
      CQ_SNYK: ${CQ_SNYK}
      GITHUB_ACCESS_TOKEN: ${GITHUB_ACCESS_TOKEN}
      SNYK_TOKEN: ${SNYK_TOKEN}
      GALAXIES_BUCKET: ${GALAXIES_BUCKET}
      CLOUDQUERY_API_KEY: ${CLOUDQUERY_API_KEY}
      DATABASE_URL: ${DATABASE_URL}
    command: sync /cloudquery.yaml --log-console --log-level info
  grafana:
    user: root
    platform: linux/amd64
    build:
      context: ../obligations-dashboard/.config
      args:
        grafana_image: ${GRAFANA_IMAGE:-grafana-oss}
        grafana_version: ${GRAFANA_VERSION:-10.3.3}
        development: ${DEVELOPMENT:-true}
    depends_on:
      - postgres
    ports:
      - '3000:3000'
    volumes:
      - ../obligations-dashboard/dist:/var/lib/grafana/plugins/theguardian-obligationsdashboard-scenesapp
      - ../obligations-dashboard:/root/theguardian-obligationsdashboard-scenesapp
      - ./config/grafana/provisioning:/etc/grafana/provisioning
    environment:
      NODE_ENV: development
      GF_LOG_FILTERS: plugin.theguardian-obligationsdashboard-scenesapp:debug
      GF_LOG_LEVEL: debug
      GF_DATAPROXY_LOGGING: 1
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: theguardian-obligationsdashboard-scenesapp
