version: '3.9'
services:
  postgres:
    image: postgres:14.6
    ports:
      - '${DATABASE_PORT}:${DATABASE_PORT}'
    environment:
      POSTGRES_DB: ${DATABASE_HOSTNAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
  cloudquery:
    build:
      context: ../../containers/cloudquery
      args:
        CQ_CLI: ${CQ_CLI}
    platform: linux/amd64
    depends_on:
      - postgres
    volumes:
      - ~/.aws/credentials:/.aws/credentials
      - ./config/cloudquery.yaml:/cloudquery.yaml
      - ~/.gu/service_catalogue/app-id:/app-id
      - ~/.gu/service_catalogue/installation-id:/installation-id
      - ~/.gu/service_catalogue/private-key.pem:/private-key.pem
    environment:
      AWS_SHARED_CREDENTIALS_FILE: '/.aws/credentials'
      CQ_POSTGRES_DESTINATION: ${CQ_POSTGRES_DESTINATION}
      CQ_AWS: ${CQ_AWS}
      CQ_GITHUB: ${CQ_GITHUB}
      CQ_SNYK: ${CQ_SNYK}
      GITHUB_ACCESS_TOKEN: ${GITHUB_ACCESS_TOKEN}
      SNYK_TOKEN: ${SNYK_TOKEN}
      GALAXIES_BUCKET: ${GALAXIES_BUCKET}
      CLOUDQUERY_API_KEY: ${CLOUDQUERY_API_KEY}
    command: sync /cloudquery.yaml --log-console --log-level info
  grafana:
    image: grafana/grafana-oss:10.3.1
    depends_on:
      - postgres
    ports:
      - '3000:3000'
    volumes:
      - ./config/grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./config/grafana/provisioning:/etc/grafana/provisioning
