version: '3.9'
services:
  postgres:
    image: postgres:14.6
    ports:
      - '${DATABASE_PORT}:${DATABASE_PORT}'
    environment:
      POSTGRES_DB: ${DATABASE_HOSTNAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
  steampipe:
    image: ghcr.io/turbot/steampipe:latest
    ports:
      - '9193:9193'
    environment:
      STEAMPIPE_DATABASE_PASSWORD: steampipe
      GITHUB_TOKEN: (secret)
    entrypoint:
      [
        '/bin/sh',
        '-c',
        'steampipe plugin install github; steampipe plugin list; steampipe service start --foreground',
      ]
  grafana:
    image: grafana/grafana-oss:9.4.7
    depends_on:
      - postgres
      - steampipe
    ports:
      - '3000:3000'
    volumes:
      - ./dev-config/grafana.ini:/etc/grafana/grafana.ini
      - ./dev-config/grafana-datasource.yaml:/etc/grafana/provisioning/datasources/cloudquery.yaml
