# Find full documentation here https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions
name: CI

on:
  pull_request:

  # Manual invocation.
  workflow_dispatch:

  push:
    branches:
      - main
jobs:
  CI:
    timeout-minutes: 15
    runs-on: ubuntu-latest

    # See https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token
    permissions:
      # required by aws-actions/configure-aws-credentials
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3

      # Setup AWS credentials to enable uploading to S3 for Riff-Raff.
      # See https://github.com/aws-actions/configure-aws-credentials
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.GU_RIFF_RAFF_ROLE_ARN }}
          aws-region: eu-west-1

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      # Configuring caching is also recommended.
      # See https://github.com/actions/setup-java
      - name: Setup Java 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'corretto'
          cache: 'sbt'

      - uses: actions/setup-go@v4
        with:
          go-version: "1.19"

      - name: Run script/ci
        run: ./scripts/ci.sh

      - name: Upload to riff-raff
        uses: guardian/actions-riff-raff@v2
        with:
          app: service-catalogue
          buildNumber: ${{ env.GITHUB_RUN_NUMBER }}
          projectName: deploy::service-catalogue
          configPath: packages/cdk/cdk.out/riff-raff.yaml
          contentDirectories: |
            cdk.out:
              - packages/cdk/cdk.out
            github-data-fetcher:
              - packages/github-data-fetcher/dist/github-data-fetcher.zip
            github-lens-api:
              - packages/github-lens-api/dist/github-lens-api.zip
            services-api:
              - packages/services-api/dist/services-api.zip
            cloudformation-lens:
              - packages/cloudformation-lens/cloudformation-lens
            repocop:
              - packages/repocop/target/scala-3.2.1/repocop.jar

    env:
      NODE_OPTIONS: '--max_old_space_size=4096'
