# Find full documentation here https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions
name: Release image

on:
  workflow_call:
    inputs:
      IMAGE_NAME:
        required: true
        type: string
      BUILD_ARGS:
        required: false
        default: ''
        type: string
        description: 'Arguments to pass to the Docker build via --build-args.'

env:
  REGISTRY: ghcr.io
  IMAGE_PATH: ${{ github.repository }}/${{ inputs.IMAGE_NAME }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4fd812986e6c8c2a69e18311145f9371337f27d4 # v3.4.0

      - name: Log in to the Container registry
        uses: docker/login-action@0d4c9c5ea7693da7b068278f7b52bda2a190a446 # v3.2.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@8e5442c4ef9f78752691e2d8f8d19755c6f78e81 # v5.5.1
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_PATH }}
          tags: |
            type=raw,value=latest
            type=sha,format=long
            type=raw,value=stable,enable={{is_default_branch}}

      - name: Build and push Docker image
        uses: docker/build-push-action@a254f8ca60a858f3136a2f1f23a60969f2c402dd # v6.4.0
        with:
          context: ./containers/${{ inputs.IMAGE_NAME }}
          file: containers/${{ inputs.IMAGE_NAME }}/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: ${{ inputs.BUILD_ARGS }}
