name: Snyk

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  security:
    uses: guardian/.github/.github/workflows/sbt-node-snyk.yml@main
    with:
      ORG: guardian-devtools
      SKIP_NODE: false
      SKIP_PYTHON: false
      PYTHON_VERSION: '3.11'
      PIP_REQUIREMENTS_FILES: packages/repocop/requirements-dev.txt
      EXCLUDE: cdk
    secrets:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
