name: Snyk
on:
  push:
    branches:
      - main
      - integrate-snyk-60b13c9780a1230b
  workflow_dispatch: 
jobs:
  security:
    uses: guardian/.github/.github/workflows/sbt-node-snyk.yml@main
    with:
      ORG: <SNYK_ORG_ID>
      SKIP_NODE: true
    secrets:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
