name: Snyk

on:
  push:
    branches:
      - main
  workflow_dispatch:


jobs:
  security:
    uses: guardian/.github/.github/workflows/sbt-node-snyk.yml@main
    with:
      DEBUG: true
      ORG: guardian-devtools
      SKIP_NODE: false
      EXCLUDE: cdk,common,github-data-fetcher,github-lens-api,services-api
    secrets:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
