name: Snyk

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  security:
    uses: guardian/.github/.github/workflows/sbt-node-snyk.yml@main
    with:
      DEBUG: true
      ORG: guardian-devtools
      SKIP_NODE: false
      NODE_PACKAGE_JSON_FILES_MISSING_LOCK: packages/cdk/package.json packages/github-lens-api/package.json packages/common/package.json packages/repo-fetcher/package.json packages/services-api/package.json
    secrets:
       SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
